plugins {
    id "com.android.application"
}

def ciDebugKeystore = System.getenv("CI_DEBUG_KEYSTORE")

android {
    namespace "com.leowood.gmsfastpairdiagnostics"
    compileSdk 35

    defaultConfig {
        applicationId "com.leowood.gmsfastpairdiagnostics"
        minSdk 27
        targetSdk 35
        versionCode 25
        versionName "0.9.7"
    }

    signingConfigs {
        if (ciDebugKeystore != null && !ciDebugKeystore.trim().isEmpty()) {
            debug {
                storeFile file(ciDebugKeystore)
                storePassword "android"
                keyAlias "androiddebugkey"
                keyPassword "android"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    compileOnly "de.robv.android.xposed:api:82"
}
